#cloud-config

runcmd:
  # Update Apt and fetch required tools.
  - apt-get -y update
  - apt-get -y install git bash
  - apt-get -y install build-essential
  # Ensure environment is setup.
  - export HOME=/root
  # Fetch and install Chef.
  - curl -L https://omnitruck.chef.io/install.sh | sudo bash
  - /opt/chef/embedded/bin/gem install berkshelf
  # Check-out the environment cookbook.
  - git clone https://github.com/darkarnium/41h.git /tmp/provisioning
  # Create the Chef zero repository.
  - cd /tmp/provisioning/41h
  - /opt/chef/embedded/bin/berks vendor
  - mkdir /tmp/chef
  - mv ./berks-cookbooks /tmp/chef/cookbooks
  - cd /tmp/chef/cookbooks
  # Kick off chef.
  - echo '{}' > /tmp/chef/chef.json
  - chmod 600 /tmp/chef/chef.json
  - chef-client -z -o '41h::default,41h::nginx' -j /tmp/chef/chef.json
