name '41h'
maintainer '0x4F'
maintainer_email 'wut@example.org'
description '0x4F CTF Bootstrap'
long_description '0x4F CTF Bootstrap'
version '0.2.1'

depends 'apt', '= 5.0.1'
depends 'yum', '= 5.1.0'
depends 'yum-epel', '= 2.1.2'
depends 'ntp', '= 3.2.0'
depends 'sysctl', '= 0.8.1'
depends 'build-essential', '= 7.0.3'
