name '41h'
maintainer '0x4F'
maintainer_email 'wut@example.org'
description '0x4F CTF Bootstrap'
long_description '0x4F CTF Bootstrap'
version '0.2.0'

depends 'apt', '~> 5.0.0'
depends 'ntp', '~> 3.2.0'
depends 'sysctl', '~> 0.8.0'
depends 'iptables', '= 3.0.1'
depends 'poise-python', '~> 1.5.1'
depends 'build-essential', '~> 7.0.1'
