name '4f_41h'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures 4f_41h'
long_description 'Installs/Configures 4f_41h'
version '0.1.0'

depends 'apt', '~> 5.0.0'
depends 'build-essential', '~> 7.0.1'
